#!/usr/bin/env php
PHP_BIN="$OPENSHIFT_DIY_DIR/runtime/php5/bin"
COMPOSER_DIR="$OPENSHIFT_DATA_DIR/bin"
APP_PATH=$OPENSHIFT_REPO_DIR/${APP_DIR}

if [ ! -f "${APP_PATH}" ]; then
  echo "Git cloning from ${APP_GIT}"
  cd $OPENSHIFT_REPO_DIR
  git clone --quiet ${APP_GIT} ${APP_DIR}
else
  echo "Git pulling"
  cd $APP_PATH
  git pull --quiet
fi

cd $APP_PATH

cp .env.openshift.example .env

if [ ! -f "${APP_PATH}/vendor" ]; then
  $PHP_BIN/php $COMPOSER_DIR/composer.phar install
else
  $PHP_BIN/php $COMPOSER_DIR/composer.phar update
fi

$PHP_BIN/php artisan key:generate
