#!/bin/bash
APP_PATH=$OPENSHIFT_REPO_DIR/${APP_DIR}

if [ ! -f "${APP_PATH}" ]; then
  echo "Git cloning from ${APP_GIT}"
  cd $OPENSHIFT_REPO_DIR
  git clone --quiet ${APP_GIT} ${APP_DIR}
else
  echo "Git pulling"
  cd $APP_PATH
  git pull --quiet
fi

cd $APP_PATH

if [ ! -f "${APP_PATH}/vendor" ]; then
  php $COMPOSER_DIR/composer.phar install
else
  php $COMPOSER_DIR/composer.phar update
fi